version: '3.3'
services:
  postgres:
    hostname: db
    image: postgres:12
    container_name: green_house
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: greenhouse
    ports:
      - 5432:5432
